---
#become: yes
- name: Create the mongodb-org yum repo file.
  become: yes
  command: touch /etc/yum.repos.d/mongodb-org-3.6.repo
  args:
    creates: /etc/yum.repos.d/mongodb-org-3.6.repo

- name: Updating the mongodb-org yum repo configuration
  blockinfile:
    dest: /etc/yum.repos.d/mongodb-org-3.6.repo
    block: |
      [mongodb-org-3.6]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc
